# Generated by Django 5.1.4 on 2025-03-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypoll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
